
async function getCharacter() {
  const res = await fetch("https://rickandmortyapi.com/api/character/2");
  return res.json();
}

export default async function Head() {
  const character = await getCharacter();
  console.log(character);
  return (
    <>
      <title>{character.name}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
